### ISSUE TITLE
Not all tweets collected

### ISSUE THREAD

**Issue by codename5281** [Mottl/GetOldTweets3#1]
Hello,
Thanks to the contributors for this work !

I am having issues collecting all tweets related to a hashtag using the --querysearch argument.
Interestingly, the low number of tweets i am retrieving seem to be sampled from the whole database (i am obtaining tweets from as soon as 2011 even though my topic of interest has been buzzing in september 2018), and  the number of tweets and the tweets themselves retrieved using a given query are still the same.

Going through Twitter search page by hand gives me the expected results, though, i.e. a lot of recent tweets.

I tried to use another ISP but the results remain the same.

Do you have any idea of where this could come from ?
I am using Python 3.7.2.

Thanks in advance,
Best,
J.

**Comment by Mottl** [comment]
Please, provide with the debug.log (using the `--debug` switch):
```GetOldTweets ... --debug > debug.log```
You can upload `debug.log` somewhere like pastebin.com since it can be really large.

**Comment by codename5281** [comment]
Thanks for your answer. You'll fing the log [at this address](https://wetransfer.com/downloads/5f5ffead0fdd335be050027ecadac40720181103131206/c99d06ec0d8175817deb26d5e796335520181103131206/b002ad)

**Comment by Mottl** [comment]
Please upgrade to 0.0.6 since 0.0.5 introduced error preventing getting all of the tweets

**Comment by codename5281** [comment]
Seems to work like a charm now ! Thanks.

**Comment by afzal646** [comment]
now this same problem comes with me
i am using 0.0.10
here is my log file:: 
[test.log](https://github.com/Mottl/GetOldTweets3/files/3438361/test.log)
