### ISSUE TITLE
Issue to run the script

### ISSUE THREAD

**Issue by KevGianecchine** [Mottl/GetOldTweets3#10]
Hi,

I have an error when run GetOldTweets because the script not found and say: module 'GetOldTweets3' has no attribute 'manager'

**Comment by Mottl** [comment]
Please provide with all steps you done to reproduce this issue.
Also OS, Python version and the method you have used to install GetOldTweets3

**Comment by KevGianecchine** [comment]
I am using Windows and Python 3.7.

I installed GetOldTweets3 with the command: pip install GetOldTweets3 and then use the command GetOldTweets3 --username "barackobama" --maxtweets 1 to try and in this moment i have the problem: module 'GetOldTweets3' has no attribute 'manager'

**Comment by KevGianecchine** [comment]
Thanks, problem fixed.
