### ISSUE TITLE
Issue with --near

### ISSUE THREAD

**Issue by Geor23es** [Mottl/GetOldTweets3#11]
Hi, when i try to collect tweets from specific location it doesn't take into account the country. For example i tried --near "Vienna, Austria" and it returned tweets from California.

**Comment by Mottl** [comment]
Rechecked: to me it works as expected.
Please, compare tweets manually with those from https://twitter.com/search-advanced

**Comment by Geor23es** [comment]
i tried this 
GetOldTweets3 --querysearch "holidays Greece" --since 2018-10-19 --until 2018-10-31 --near "Vienna, Austria" --within 1500mi

and one of the tweets was this:
https://twitter.com/_AminaMoloto_/status/1056360983944486914

which has geolocation South Africa and with my search i was supposed to be getting tweets from Europe

**Comment by Mottl** [comment]
Have you compared with what Twitter's advanced search give you (the link above)?

**Comment by Geor23es** [comment]
yes and it returns different tweets.
Am i writing something wrong when i call the script?

**Comment by Mottl** [comment]
> and one of the tweets was this:
> https://twitter.com/_AminaMoloto_/status/1056360983944486914

I issued the same query and didn't get this tweet. Please, send debug.log along with the `got_output.csv`.

**Comment by Geor23es** [comment]
I deleted everything and i downloaded again the repository and everything works fine now. thank you for your time.

**Comment by afzal646** [comment]
**how can i get city name and cordinates of each tweet?**
