### ISSUE TITLE
[New feature] Add "replies count" field for Tweet

### ISSUE THREAD

**Issue by carlosabcs** [Mottl/GetOldTweets3#12]
Is there a way to add the number of replies that a Tweet received? I think it would be similar to the favorites and retweets fields.

Wouldn't it be adding a line like this one?
```python
tweet.replies = int(tweetPQ("span.ProfileTweet-action--reply span.ProfileTweet-actionCount").attr("data-tweet-stat-count").replace(",", ""))
```
After https://github.com/Mottl/GetOldTweets3/blob/master/GetOldTweets3/manager/TweetManager.py#L87

**Comment by Mottl** [comment]
Great, man!

https://github.com/Mottl/GetOldTweets3/releases/tag/0.0.8

pip package updated as well:  
https://pypi.org/project/GetOldTweets3/#history
