### ISSUE TITLE
Problem getting started (SyntaxError)

### ISSUE THREAD

**Issue by meikefrdrchs** [Mottl/GetOldTweets3#14]
Hi, I wanted to use GetOldTweets3 to download the tweets of a userlist and went through the installation using `sudo pip install -e git+https://github.com/Mottl/GetOldTweets3#egg=GetOldTweets3` but whatever I do, even if I just want to call the -h, it just gives me an error:

`Traceback (most recent call last):`
  `File "/usr/local/bin/GetOldTweets3", line 6, in <module>`
    `exec(compile(open(__file__).read(), __file__, 'exec'))`
  `File "/GetOldTweets3-master/src/getoldtweets3/bin/GetOldTweets3", line 144`
    `nonlocal cnt`
      `         ^`
`SyntaxError: invalid syntax`

The old GetOldTweets by Jefferson-Henrique works without a problem and I'm at a bit of a loss since I don't know anything about the nonlocal statement in this context. Could somebody maybe help me out here?

**Comment by Mottl** [comment]
GetOldTweets3 is not compatible with Python 2.7.
Please use Python 3.

**Comment by meikefrdrchs** [comment]
I actually do but I just realised it appears to be using the Apple-built in Python 2.7 so I'll try to find out if there's any way to stop it from using 2.7 even if the code has ` #!/usr/bin/env python3`
