### ISSUE TITLE
How can I specify the time?

### ISSUE THREAD

**Issue by nanu1129** [Mottl/GetOldTweets3#16]
Update to the latest version of GetOldTweets3 before committing the issue!

**Describe the bug**

**debug.log**
Run GetOldTweets with the `--debug` option:
```
GetOldTweets ... --debug > debug.log
```

Upload `debug.log` to somewhere like [http://gist.github.com](gist.github.com) or  [https://pastebin.com](pastern.com) and provide with the link to your `debug.log`.

**For general issues with running GetOldTweets3**
If you have a general question please provide with OS, Python version and the method you have used to install GetOldTweets3

**Comment by Mottl** [comment]
You can't

**Comment by nanu1129** [comment]
Can you tell me how to specify the time somehow
