### ISSUE TITLE
results show just for 7 past days

### ISSUE THREAD

**Issue by shahmohamadi** [Mottl/GetOldTweets3#19]
this code worked fine and give back results by --querysearch from 2009 to 2019, but now it only gives me tweets for 7 days ago.
I also do changes in https://github.com/Jefferson-Henrique/GetOldTweets-python/issues/230 but it doesn't work.

**Comment by Mottl** [comment]
Please provide with the full information including the `debug.log`

**Comment by RishiKapadia20** [comment]
Having the same issue, I was able to use your tool for one day but then when I tried running the same script the next day it would not return anything past 1 week :( not sure why?

**Comment by Mottl** [comment]
Can say nothing without debug.log

**Comment by RishiKapadia20** [comment]
how do i get a debug.log?

**Comment by Mottl** [comment]
Just add `--debug` option and redirect to a file:
```GetOldTweets <your-options-go-here> --debug > debug.log```

**Comment by RishiKapadia20** [comment]
Command: GetOldTweets3 --querysearch "American Airlines" --since 2018-02-15 --until 2018-02-19 --maxtweets 10 --debug > debug.log

[debug.log](https://github.com/Mottl/GetOldTweets3/files/2890351/debug.log)

output_got.csv is empty

**Comment by Mottl** [comment]
I can get the tweets using exactly the same query. Possibly, your IP is banned by Twitter. Can you try from a different IP/host?

**Comment by RishiKapadia20** [comment]
Tried on a aws vm seems to work fine as well seems to be an ip block. I'm trying to collect a large amount of tweets for a school project is there anyway to stop getting IP blocked?

**Comment by Mottl** [comment]
Me personally not :-)

**Comment by inactivist** [comment]
FWIW, if you aren't seeing the expected results a day or so after using it successfully: Twitter may throttle your IP address temporarily when they detect automated scraping.  It appears they analyze daily activity and will limit you for a while, then remove the limit after a day or so.  As of my last investigation, Twitter did this using a combination of IP address and user agent, so if you can't change your IP address, randomizing the user agent may help 

**Edit** I see `GetOldTweets3` does attempt to randomize UA per run.  Investigating...

More info in [this SO issue](https://stackoverflow.com/questions/45906631/urllib-request-urlopen-is-behaving-strange-not-returning-the-data-the-next-day/48031220#48031220)
