### ISSUE TITLE
new features

### ISSUE THREAD

**Issue by Arwa200** [Mottl/GetOldTweets3#20]
hi, 
thank you for great tool, it was very helpful
I am wondering, if there is any future plane to add new features such as collect all historical retweets and favorites?

**Comment by Mottl** [comment]
Hi, what do you mean by that? Retweets and favorites counters are already available.

**Comment by Arwa200** [comment]
I meant favorite and retweeted tweets not counters..

**Comment by Mottl** [comment]
Are you sure that's possible? This is the search form https://twitter.com/search-advanced used by GetOldTweets3

**Comment by Arwa200** [comment]
Well, yes you are right, using advanced search seems like it is not possible..
sorry, I did not recognize that GetOldTweets 3 used advance search
Thank you for your response..

**Comment by Mottl** [comment]
You are welcome!

**Comment by inactivist** [comment]
> Are you sure that's possible? This is the search form https://twitter.com/search-advanced used by GetOldTweets3

You may use the [`filter:nativeretweets` operator](http://followthehashtag.com/help/hidden-twitter-search-operators-extra-power-followthehashtag/) to retrieve a list of retweets.
