### ISSUE TITLE
Remove Warnings from code

### ISSUE THREAD

**Issue by giulionf** [Mottl/GetOldTweets3#22]
Rename all variables and fix code structure to meet Python pep8 guidelines

**Comment by Mottl** [comment]
Hi, @giulionf
Renaming API class methods and variables will break backward compatibility.

**Comment by giulionf** [comment]
@Mottl okay I see... I've made a new Pull request with only the concurrency changes. Can you have a look at that?

**Comment by giulionf** [comment]
You could do a migration where you had a deprecated function that calls the new one with supressed warnings. That would solve the problem I guess, wouldn't it?

**Comment by Mottl** [comment]
I think that PEP8 warnings are not a big issue. If you have time it's better to rewrite the fetching logic https://github.com/Mottl/GetOldTweets3/issues/3#issuecomment-439092370

**Comment by giulionf** [comment]
Alright then. I will for sure try to work on that issue!

**Comment by Mottl** [comment]
That's will be really great, @giulionf
