### ISSUE TITLE
Geocode search

### ISSUE THREAD

**Issue by mariyamilosh** [Mottl/GetOldTweets3#24]
Hi there,
I am trying to scrape tweets from a geographic coordinates point (not by place name!). Twitter search allows it with a query: "geocode:latitude,longitude,radius around the point". As there is no argument in the parser to specify geocode, I tried to just put my geocode into the query and search. Looks like Twitter generally gets it. But sometimes it gives inconsistent results:

```
query = 'geocode:30.3255568815976,-81.7671865745302,0.578km'
tweetCriteria = got.manager.TweetCriteria().setQuerySearch(query)
storage = got.manager.TweetManager.getTweets(tweetCriteria)
```
or

`GetOldTweets3 --querysearch "geocode:30.3255568815976,-81.7671865745302,0.578km"`

gives 5 tweets, but there are about 90 if I search the same query in Twitter [manually](https://twitter.com/search?q=geocode%3A30.3255568815976%2C-81.7671865745302%2C0.578km&src=typd&lang=en).

Could this be happening because I use set.QuerySearch to search by coordinates instead of, say, set.Geocode (if this existed, which would be awesome, by the way)? If not, do you have any ideas why this is happening? Thanks!

Log file [here](https://gist.github.com/mariyamilosh/965344cfb1a3b2fa98e04f2856aa1ed8)

**Comment by Mottl** [comment]
Seems like the same bug as https://github.com/Mottl/GetOldTweets3/issues/3

p.s.
[0.0.10](https://github.com/Mottl/GetOldTweets3/releases/tag/0.0.10) supports search by geo coordinates using `--near` parameter.
