### ISSUE TITLE
How to use GetOldTweets3

### ISSUE THREAD

**Issue by TobiasEl** [Mottl/GetOldTweets3#25]
Hello.
Excuse me if this question is so stupid, buy how I use the GetOldTweets3 command??
I'm inside the folder GetOldTweets3-master and I run the example:
**GetOldTweets3 --username "barackobama" --maxtweets 1**
or
**GetOldTweets3 -h**

But I have: "GetOldTweets3 it is not recognized as an internal or external command,
program or batch file executable"

Exactly what I have to write where it said "GetOldTweets3" to run the code??

Thank you.

**Comment by Mottl** [comment]
```sudo pip install GetOldTweets3```
and then run GetOldTweets3 from the folder where your Python packages are located (type `echo "import sys; print(sys.path);" | python3` in unix command line to get the list of package folders).
