### ISSUE TITLE
Help in running command line

### ISSUE THREAD

**Issue by leolizm** [Mottl/GetOldTweets3#26]
I have never done this kind of thing before and usually never had to refer to an external library and hope I can get help here. So, I am trying to make sure I can run the command line to extract tweets to csv directly. My error is as follows: 

>>> GetOldTweets3 -h
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'h' is not defined

The pip will install the GetOldTweets3 folder into the site-packages. If I could get a tutorial on how and where to run command lines, that would be really helpful.

**Comment by Mottl** [comment]
Can you run GetOldTweets3 explicitly with python 3 interpreter (e.g. `python3 /path/to/GetOldTweets3`)?

**Comment by leolizm** [comment]
I am able to import GetOldTweet3, but I am not able to run with the path file. 
My path for GetOldTweets3 is: 
C:\Users\leopu\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\GetOldTweets3

**Comment by Mottl** [comment]
Can you invoke this:  
python3 C:\Users\leopu\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\GetOldTweets3
