### ISSUE TITLE
I get 0 tweets

### ISSUE THREAD

**Issue by AntonioNieto92** [Mottl/GetOldTweets3#27]
Hello,

When I request tweets I don't receive any one. Yesterday it worked perfectly well

Do you know what can be the problem?

**Comment by JohnDickson5** [comment]
I am also having this problem. Last night at 9pm EST it was working; today every search returns an empty dictionary.

**Comment by AntonioNieto92** [comment]
Think that Twitter banned us for doing multiple queries

**Comment by JohnDickson5** [comment]
Based on comments in Jefferson-Henrique/GetOldTweets-python, I thought the same, but it seems like a rather large coincidence that it would happen the same day to both of us. I am going to try it on another network.

**Comment by giulionf** [comment]
Issue already exists. Please close this and discuss in the specific topic.
https://github.com/Mottl/GetOldTweets3/issues/3

**Comment by JohnDickson5** [comment]
I'm afraid I don't follow the discussion in that topic. Is the takeaway "try a different device", or is there a way to code a fix?

**Comment by giulionf** [comment]
The takeaway is that issues should not be opened twice since all  that is necessarry has already been discussed in the issue i linked :) TLDR: The fix is not known but another user suggested what has to be done to get rid of this behaviour with a very high confidence... No one seems to be working on it actively at the moment.

**Comment by Mottl** [comment]
> Hello,
> 
> When I request tweets I don't receive any one. Yesterday it worked perfectly well
> 
> Do you know what can be the problem?

Please, provide with the `debug.log`:  
```GetOldTweets3 ... --debug > debug.log```

**Comment by JohnDickson5** [comment]
[debug.log](https://github.com/Mottl/GetOldTweets3/files/3169592/debug.log)

output_got.csv:
date,username,to,replies,retweets,favorites,text,geo,mentions,hashtags,id,permalink

**Comment by Mottl** [comment]
@JohnDickson5 

Please add `--debug` option to your command:
```GetOldTweets3 ... --debug > debug.log```

**Comment by JohnDickson5** [comment]
the above is what I get with the --debug option

**Comment by Mottl** [comment]
`--debug` option should output the version of GetOldTweest3:
```~/src/GetOldTweets3/bin/GetOldTweets3 --debug
GetOldTweets3 0.0.9
Downloading tweets...```
