### ISSUE TITLE
How can i get Tweets that contains at least one of the keywords provided in QuerySearch()

### ISSUE THREAD

**Issue by Amrouane** [Mottl/GetOldTweets3#28]
I wonder if there is a way I can retrieve tweets with at least one of the keywords provided by the query search method.
I've tried this: 
```
tweetCriteria = got.manager.TweetCriteria().setQuerySearch('europe refugees')\
                                           .setSince("2015-05-01")\
                                           .setUntil("2015-09-30")\
                                           .setMaxTweets(10)
tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
print(tweet.text)
```
But I get in return the tweets that contain the two keywords europe and refugees. I want  the first 10 tweets that contain either europe or refugees. Is this possible ?

**Comment by giulionf** [comment]
Use setQuerySearch("Europe OR Refugees").
It's the way Twitter Formats multiple keywords. 

Just a reminder... Issues are Not for questions, but for problems with the code itself! :)

**Comment by Amrouane** [comment]
Thanks, I'll take that into consideration next time
