### ISSUE TITLE
Similar alternative for getting Followers / Followings list ? 

### ISSUE THREAD

**Issue by codepujan** [Mottl/GetOldTweets3#31]
Great library fo immense utility. Kudos to the developers. 
I was wondering if there's a similar utility tool to grab the followers of a user too? It'd be extremely important application wise since the rate limit on downloading Followers/ Followings are even more painful than that of the tweets. 
if there's already an existing solution or other alternatives, would you let me know?

**Comment by Mottl** [comment]
I don't know whether such a script is already made but you can do it quite easy. Just parse the page of followers `http://twitter.com/{USERNAME}/followers` (for example https://twitter.com/barackobama/followers)
