### ISSUE TITLE
Words from queries that contain the $ symbol are ignored

### ISSUE THREAD

**Issue by gghidiu** [Mottl/GetOldTweets3#33]
I need to search for tweets that contain a company name (e.g. Apple) AND the stock ticker symbol (e.g. $APPL). However, if I use the following command: 

**GetOldTweets3 --querysearch "Apple $APPL lang:en"  --maxtweets 10**

then the word $APPL is not present in any of the tweets in the output doc.

The same happens with any word that starts with $ symbol. The tool somehow ignores such words. What can I do to solve this issue?

Thank you in advance and thanks for the very useful tool.

**Comment by Mottl** [comment]
`$APPL` in the example above treats as a shell variable. For the proper use change double quotes to single ones:
```GetOldTweets3 --querysearch 'Apple $APPL lang:en' --maxtweets 10```

Full explanation: https://stackoverflow.com/a/6697781/9947010
