### ISSUE TITLE
Exact number of tweet from different location

### ISSUE THREAD

**Issue by irfanprabaswara** [Mottl/GetOldTweets3#34]
I try to run my query like this 

tweetCriteria = got.manager.TweetCriteria().setQuerySearch('#Barcelona')\
                                            .setSince("2017-01-01")\
                                            .setUntil("2018-12-31")\
                                            .setNear("'Medan, Indonesia'")\
                                            .setMaxTweets(100000000) 

I got 1559 tweets for this code. Than I try to change the location using this query

tweetCriteria = got.manager.TweetCriteria().setQuerySearch('#Barcelona')\
                                            .setSince("2017-01-01")\
                                            .setUntil("2018-12-31")\
                                            .setNear("'Jambi, Indonesia'")\
                                            .setMaxTweets(100000000) 

I got 1559 tweets too. Logically, this is not true. Am I doing something wrong?

**Comment by Mottl** [comment]
The problem is with the quote inside `setNear` function argument:
The correct usage is `.setNear("Medan, Indonesia")`
