### ISSUE TITLE
How to export all tweets in csv file?

### ISSUE THREAD

**Issue by afzal646** [Mottl/GetOldTweets3#39]
Update to the latest version of GetOldTweets3 before committing the issue!

**Describe the bug**

**debug.log**
Run GetOldTweets with the `--debug` option:
```
GetOldTweets ... --debug > debug.log
```

Upload `debug.log` to somewhere like [http://gist.github.com](gist.github.com) or  [https://pastebin.com](pastern.com) and provide with the link to your `debug.log`.

**For general issues with running GetOldTweets3**
If you have a general question please provide with OS, Python version and the method you have used to install GetOldTweets3

**Comment by Rannita** [comment]
I didn't find the answer to the question: how to export all the tweets in csv file ?
