### ISSUE TITLE
Can we set since parameter with format YYYY-MM-DD HH:MM:SS or YYYY-MM-DD HH:MM  ?

### ISSUE THREAD

**Issue by JaimeBadiola** [Mottl/GetOldTweets3#4]
I tested this option and it does not properly work. 

Here is the log [link](https://gist.github.com/JaimeBadiola/2ef17c63b11a3a732ccd74f31f29e599)

The log did not properly worked either, so here is the command line query:

python Exporter.py --querysearch "europe refugees" --maxtweets 1000 --since 2018-02-21 18:00:00 --debug > debug.log

**Comment by Mottl** [comment]
Since Twitter changed something on their side it is not possible to specify time in `--since` and `--until` parameters anymore.

**Comment by JaimeBadiola** [comment]
Not even with the format YY-MM-DD ?

Thanks for all your help!

**Comment by Mottl** [comment]
Only `YYYY-MM-DD`

**Comment by JaimeBadiola** [comment]
Ok Thanks a lot! 

the script is being a great help!
