### ISSUE TITLE
Just Can Get Tweets for This Month

### ISSUE THREAD

**Issue by irfanprabaswara** [Mottl/GetOldTweets3#41]
I try to get using command 
GetOldTweets3 --username "barackobama" --since 2015-09-10 --until 2015-09-12 --maxtweets 10
and I got nothing
Then I try to delete the time range like this
GetOldTweets3 --username "barackobama"
I got the tweet, but just for this month
How can I fix this problem?
I need tweets for last 10 years

**Comment by afzal646** [comment]
i am also facing the same problem
How can I fix this problem?

**Comment by Mottl** [comment]
Can't say much without a log file

**Comment by afzal646** [comment]
i want all tweets with #FawadAlamExposed but i am getting only 28 tweets but if use tweter advanced search option i give a a lot of tweets more than 28 
how can i resolve this issue?
My code
`import GetOldTweets3 as got
import logging

logging.basicConfig(filename="test.log",level=logging.DEBUG)

tweetCriteria = got.manager.TweetCriteria().setUsername("#FawadAlamExposed")\
                                                                      .setMaxTweets(100)



for i in range(99):
    tweet = got.manager.TweetManager.getTweets(tweetCriteria)[i]
    print(tweet.text)
    f = open("tweets.txt", "a" , encoding="utf-8")
    f.write(tweet.text+"\n\n")`

log file::
[test.log](https://github.com/Mottl/GetOldTweets3/files/3433822/test.log)

**Comment by afzal646** [comment]
thanku issue is resolved!

**Comment by afzal646** [comment]
thanku issue resolved!

**Comment by johnguacala** [comment]
@afzal646  how do you solve it?
I'm facing the same issue?

**Comment by jtaylor351** [comment]
Scraping by username is disallowed in Twitter's robots.txt, so your IP address might be temporarily blocked for not following the robots.txt

**Comment by Mottl** [comment]
Seems like your IP was blocked by Tweeter

**Comment by Ayuu713** [comment]
> I try to get using command
> GetOldTweets3 --username "barackobama" --since 2015-09-10 --until 2015-09-12 --maxtweets 10
> and I got nothing
> Then I try to delete the time range like this
> GetOldTweets3 --username "barackobama"
> I got the tweet, but just for this month
> How can I fix this problem?
> I need tweets for last 10 years

You are getting the latest 10 tweets for scraping tweets of 1 month you need to increase the tweets count
