### ISSUE TITLE
Problem with VPN 

### ISSUE THREAD

**Issue by Appotrooper** [Mottl/GetOldTweets3#44]
`Hi,` 

First, let me say thank you for your work! you have made my life so much easier in the last couple month. 
Secondly, the program has been working flawlessly until today. Let me explain the issue. I use windows 10, pycharm, and run getoldtweet bash on ubuntu. The program still works when I am not connected to a VPN. However, in the past (until yesterday) I was able to run GetOldTweets3 without any issues when I was connected to my VPN. 
I have attached the debug file and any help would be wonderful. I have not changed anything so I am not sure what is happening... 
 
```
> GetOldTweets3 0.0.10
> Downloading tweets...
> https://twitter.com/i/search/timeline?f=tweets&vertical=news&q=Possession%20since%3A2012-05-30%20until%3A2012-09-04&src=typd&&include_available_features=1&include_entities=1&max_position=&reset_error_state=false
> Host: twitter.com
> User-Agent: Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko
> Accept: application/json, text/javascript, */*; q=0.01
> Accept-Language: en-US,en;q=0.5
> X-Requested-With: XMLHttpRequest
> Referer: https://twitter.com/i/search/timeline?f=tweets&vertical=news&q=Possession%20since%3A2012-05-30%20until%3A2012-09-04&src=typd&&include_available_features=1&include_entities=1&max_position=&reset_error_stat
> e=false
> Connection: keep-alive
> An error occured during an HTTP request: <urlopen error [Errno -3] Temporary failure in name resolution>
> Try to open in browser: https://twitter.com/search?q=Possession%20since%3A2012-05-30%20until%3A2012-09-04&src=typd
> 
> Done. Output file generated "output_got.csv".
```
https://gist.github.com/Appotrooper/adc89b1976e0dc96a4caa726103e9742

Thanks in advance!

**Comment by Appotrooper** [comment]
I ended up uninstalling ubuntu and Pycharm and it is working again.

**Comment by Mottl** [comment]
Seems like you had a problem with DNS server when you are connected through VPN:
```An error occured during an HTTP request: <urlopen error [Errno -3] Temporary failure in name resolution>```
