### ISSUE TITLE
error in extracting all tweets

### ISSUE THREAD

**Issue by darreldoctor** [Mottl/GetOldTweets3#47]
hello!
I was trying to extract tweets by running 
python3 /Users/Jham/src/getoldtweets3/bin/GetOldTweets3 --usernames-from-file userlist.txt --since 2017-01-01 --until 2017-12-31

but I keep getting the following error:
Found 94 usernames in userlist.txt
Downloading tweets...
Saved 600Traceback (most recent call last):
  File "/Users/Jham/src/getoldtweets3/bin/GetOldTweets3", line 206, in main
    got.manager.TweetManager.getTweets(tweetCriteria, receiveBuffer, debug=debug)
  File "/Users/Jham/src/getoldtweets3/GetOldTweets3/manager/TweetManager.py", line 88, in getTweets
    rawtext = TweetManager.textify(tweetPQ("p.js-tweet-text").html(), tweetCriteria.emoji)
  File "/Users/Jham/src/getoldtweets3/GetOldTweets3/manager/TweetManager.py", line 190, in textify
    if "u-hidden" in attr["class"]:
KeyError: 'class'

'class'

Done. Output file generated "output_got.csv".

Thank you!!

**Comment by Arwa200** [comment]
I got only small number of tweets.. 

![Screen Shot 2019-11-02 at 10 51 19 PM](https://user-images.githubusercontent.com/42224049/68076258-5ea78e00-fdc3-11e9-8e49-88da1c5936b5.png)

**Comment by mawic** [comment]
I got the same error. My hypothesis is that a tweet contains an emoji that causes the error.  But I was not able to confirm this so far.

**Comment by Arwa200** [comment]
this is new right?  because I got a good result a few months a go

**Comment by mawic** [comment]
I found a workaround and created a pull request: https://github.com/Mottl/GetOldTweets3/pull/49

**Comment by Mottl** [comment]
Fixed 49
