### ISSUE TITLE
Always prints only one tweet. The output csv is not created. 

### ISSUE THREAD

**Issue by jyp256** [Mottl/GetOldTweets3#48]
Hi. I ran the code exactly as in the instructions.
However, it always print only one tweet no matter what, which doesn't make sense given the user and the period.
It doesn't matter whether I set the maximum number of tweets or not using .setMaxTweets(1)

Also, the output csv file is not created anywhere. How can I create the csv file containing the results?

Here are my code:

`import GetOldTweets3 as got
tweetCriteria = got.manager.TweetCriteria().setUsername("washingtonpost")  \
                                           .setSince("2019-01-01")  \
                                           .setUntil("2019-01-05")
tweet = got.manager.TweetManager.getTweets(tweetCriteria)[0]
print(tweet.text)
`

Here are the output:

C:/............../GetOldTweets.py
How to be likable, by @petridisheshttps://wapo.st/2F9uL1J

Process finished with exit code 0

**Comment by psyjm9** [comment]
Remove the [0] that you have after .getTweets(tweetCriteria)**[0]**
Then create a loop to iterate through the tweets like so:

`for tweets in tweet:`
`print(tweets.text)`
