### ISSUE TITLE
Emoji[😄😭💢] included, Tweets

### ISSUE THREAD

**Issue by kickasssss** [Mottl/GetOldTweets3#5]
Can this system get a tweet containing emoji[😄😭💢]?

very thankful for this system.
Thanks

**Comment by Mottl** [comment]
No, they are stripped from tweets.
If you need them you can improve the code around here: https://github.com/Mottl/GetOldTweets3/blob/dd0924b03991571ab25a66deaba7e89545ea61dc/GetOldTweets3/manager/TweetManager.py#L85

**Comment by kickasssss** [comment]
Thanks, response

I challenged, but it did not work...
How do you tell me how to change?

**Comment by kickasssss** [comment]
Thanks to you I succeeded. 

If you have any questions, listten again.
I look forward to working with you.

**Comment by JaimeBadiola** [comment]
@kickasssss Can you share your improvements?

**Comment by Mottl** [comment]
Great
If you want to merge your code to this fork, feel free to make a pull request. In this case please add some parameter to `bin/GetOldTweets3`, for example `--save-emoji`.

**Comment by Mottl** [comment]
> @kickasssss Can you share your improvements?

I thought you made the improvements. I don't have plans to do that.

**Comment by JaimeBadiola** [comment]
> thought

Nono I am just wondering if @kickasssss can share his improvements to the code, so I can add them, to my script

**Comment by Mottl** [comment]
> Thanks to you I succeeded.
> 
> If you have any questions, listten again.
> I look forward to working with you.

Great, you can make a pull request and I will merge you code. Consider of adding a new parameter (for example `--save-emoji`) to `bin/GetOldTweets`.

**Comment by kickasssss** [comment]
Ok.
Please also check the code together.
