### ISSUE TITLE
empty cells not divided by commas

### ISSUE THREAD

**Issue by jemielniak** [Mottl/GetOldTweets3#58]
In a CSV file generated, it appears that at least some of the cells that are empty are not marked properly - as a result the column for "favorites" contains what should be in "text", and so on - the database is unworkable as a result. 

I'm wondering if there is a way to correct this on my side.  It appears that it is broken in instances when a long www address is part of the text (with /?mbid=social_facebook&amp&utm_brand=p4k&amp... etc.) syntax

**Comment by lethalbeans** [comment]
maybe add an image of what you're talking about

**Comment by jemielniak** [comment]
Fair point. An example of a problematic row (the web address should not be divided into separate cells, but it is):


05/04/18 03:50 PM | wirewoolevents | ajktarttelin | 0 | 3 | 4 | You can meet Abigail Tarttelin in person at @OctoberBooks on June 20th! She'll be talking about #DeadGirls #feminism + much more. Tickets + further details at http://wirewoolevents.com |   | @OctoberBooks | #DeadGirls #feminism | 9.92E+17 | https://twitter.com/wirewoolevents/status/992431262278340609 |   |   | hashb=0d21ffa86be79e79e49c53fe47757525b01c14ed&amp | hashc=7cfdc8aa86c8f74c5a6443daa871a23a1e7dd5e0f25610faa690d28aa9a9d8df&amp | esrc=VOG_NWSLTR_STYSHOP2&amp | utm_term=VOG_Runway&amp
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --

**Comment by jemielniak** [comment]
OK, so I narrowed it down to two culprits that are most likely causing trouble:
&amp,
&gt",

after removing these from .csv in Notepad++, the number of broken rows dropped from 15k (out of 180k) to about 1k, which is already fine.
