### ISSUE TITLE
Keep having "Twitter weird response..." 

### ISSUE THREAD

**Issue by beckkim77** [Mottl/GetOldTweets3#6]
When I ran a command,
"GetOldTweets3 --username "barackobama" --maxtweets 1", 

I encountered following outcome,
" Downloading tweets...
Twitter weird response. Try to open in browser: https://twitter.com/search?q=%20from%3Abarackobama&src=typd
Unexpected error: <class 'urllib.error.URLError'>

Done. Output file generated "output_got.csv".

Does this problem happens only for me? Any idea how I can fix?

**Comment by Mottl** [comment]
Have you tried opening that url in browser?

**Comment by beckkim77** [comment]
I have tried the url in browser and found it works (at least in my browser).
Then I've updated GetOldTweets3 to the new version (0.0.7). I ran the same command as earlier ("GetOldTweets3 --username "barackobama" --maxtweets 1"), but now I have different error message as follows:
"Downloading tweets...
An error occured during an HTTP request: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>
Try to open in browser: https://twitter.com/search?q=%20from%3Abarackobama&src=typd"
Of course the url works well in my browser (Chrome Version 70.0.3538.77).

By the way, I realized that when I installed GetOldTweets3 on a machine at home and ran the same command, no errors came out. I strongly suspect the errors above is related to the network configuration at my workplace. I would contact the network manager. But I want to make sure my hypothesis is reasonable before I talk to him. Any ideas?

**Comment by Mottl** [comment]
Have you installed CA certificates?

**Comment by beckkim77** [comment]
Wow. I have installed Certificates in the Python3 bundle. Now GetOldTweet3 works like a charm. I really appreciate your help!

**Comment by preetham-salehundam** [comment]
@beckkim77  What do you mean by installing certificates in the python bundle? I have the same issues can you explain your fix?

**Comment by beckkim77** [comment]
> @beckkim77 What do you mean by installing certificates in the python bundle? I have the same issues can you explain your fix?

Hope this helps:
https://stackoverflow.com/questions/40684543/how-to-make-python-use-ca-certificates-from-mac-os-truststore
