### ISSUE TITLE
Script doesn't run 

### ISSUE THREAD

**Issue by mesapedrazas** [Mottl/GetOldTweets3#74]
Hi all! 

I just installed GetOldTweets3 from Anaconda3 Prompt for Win10 sucesfully, but I cannot run anything, says that GetOldTweets3 is not a recognized commmand... I know it must be a newbie error but I really need to fix this... 
Thanks!!!

**Comment by sklorton** [comment]
Same problem

**Comment by Mottl** [comment]
Find where Anaconda installed GetOldTweets3 executable file and run it from that location.
