### ISSUE TITLE
GOT THIS

### ISSUE THREAD

**Issue by deshratan45** [Mottl/GetOldTweets3#8]
An error occured during an HTTP request: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1051)>
Try to open in browser: https://twitter.com/search?q=%20from%3Abarackobama&src=typd

**Comment by Mottl** [comment]
Possibly, you have no CA certificates installed on your server.
Issue https://github.com/Mottl/GetOldTweets3/issues/6

**Comment by hussein95** [comment]
Hi frinds,i have a problem with my code ,pleas help me Th U--------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-af4751991fc9> in <module>()
     11 tweetCriteria = got.manager.TweetCriteria().setQuerySearch(' المملكة العربية السعودية الكلاسيكو ').setSince("2018-5-7").setUntil("2018-5-6").setMaxTweets(100)
     12 for i in range(100):
---> 13  tweet = got.manager.TweetManager.getTweets(tweetCriteria)[i]
     14  print(tweet.text)
     15 

IndexError: list index out of rang
