### ISSUE TITLE
Command Line Utility requires user elevation in order to be installed

### ISSUE THREAD

**Issue by chloeeggleston** [Mottl/GetOldTweets3#81]
OS: Arch Linux
Python: 3.8

Hello, I attempted both methods to install GetOldTweets3 via pip (default and git), and I found that on my system the command line utility is only installed when the user is root, or `sudo pip install GetOldTweets3`. Not sure if this is a quirk of my own python setup or something related to this package.

**Comment by Mottl** [comment]
For local installation use `pip install GetOldTweets3 --user`. Do not forget to add `~/.local/bin` to your `$PATH` environment variable.

**Comment by chloeeggleston** [comment]
Thanks! `~/.local/bin` wasn't in $PATH.
